FROM node:18

WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Expose the development port
EXPOSE 5173

# Command to start the development server
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"] 