use serde::{Deserialize, Serialize};
use super::properties::BlockProperties;

/// All block types available in the game
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[repr(u16)]
pub enum BlockType {
    // Basic blocks
    Air = 0,
    Stone = 1,
    Dirt = 2,
    Grass = 3,
    Sand = 4,
    Gravel = 5,
    Bedrock = 6,
    
    // Wood types
    OakLog = 10,
    BirchLog = 11,
    SpruceLog = 12,
    OakPlanks = 13,
    BirchPlanks = 14,
    SprucePlanks = 15,
    
    // Leaves
    OakLeaves = 20,
    BirchLeaves = 21,
    SpruceLeaves = 22,
    
    // Ores and minerals
    CoalOre = 30,
    IronOre = 31,
    GoldOre = 32,
    RedstoneOre = 33,
    DiamondOre = 34,
    
    // Processed materials
    Glass = 40,
    Brick = 41,
    Cobblestone = 42,
    StoneBrick = 43,
    
    // Fluids
    Water = 50,
    Lava = 51,
    
    // Plants
    TallGrass = 60,
    Flower = 61,
    
    // Special
    Torch = 70,
    Chest = 71,
    Crafting = 72,
    Furnace = 73,
}

impl BlockType {
    /// Returns the block properties for this block type
    pub fn properties(&self) -> BlockProperties {
        match self {
            // Basic blocks
            BlockType::Air => BlockProperties {
                name: "Air",
                solid: false,
                transparent: true,
                fluid: false,
                gravity_affected: false,
                light_emission: 0,
                blast_resistance: 0.0,
                hardness: 0.0,
                tool_type: None,
                flammable: false,
                drops: None,
            },
            BlockType::Stone => BlockProperties {
                name: "Stone",
                solid: true,
                transparent: false,
                fluid: false,
                gravity_affected: false,
                light_emission: 0,
                blast_resistance: 6.0,
                hardness: 1.5,
                tool_type: Some("pickaxe"),
                flammable: false,
                drops: Some(BlockType::Cobblestone),
            },
            BlockType::Dirt => BlockProperties {
                name: "Dirt",
                solid: true,
                transparent: false,
                fluid: false,
                gravity_affected: false,
                light_emission: 0,
                blast_resistance: 0.5,
                hardness: 0.5,
                tool_type: Some("shovel"),
                flammable: false,
                drops: Some(BlockType::Dirt),
            },
            BlockType::Grass => BlockProperties {
                name: "Grass Block",
                solid: true,
                transparent: false,
                fluid: false,
                gravity_affected: false,
                light_emission: 0,
                blast_resistance: 0.6,
                hardness: 0.6,
                tool_type: Some("shovel"),
                flammable: false,
                drops: Some(BlockType::Dirt),
            },
            BlockType::Sand => BlockProperties {
                name: "Sand",
                solid: true,
                transparent: false,
                fluid: false,
                gravity_affected: true,
                light_emission: 0,
                blast_resistance: 0.5,
                hardness: 0.5,
                tool_type: Some("shovel"),
                flammable: false,
                drops: Some(BlockType::Sand),
            },
            BlockType::Gravel => BlockProperties {
                name: "Gravel",
                solid: true,
                transparent: false,
                fluid: false,
                gravity_affected: true,
                light_emission: 0,
                blast_resistance: 0.6,
                hardness: 0.6,
                tool_type: Some("shovel"),
                flammable: false,
                drops: Some(BlockType::Gravel),
            },
            BlockType::Bedrock => BlockProperties {
                name: "Bedrock",
                solid: true,
                transparent: false,
                fluid: false,
                gravity_affected: false,
                light_emission: 0,
                blast_resistance: 3600000.0,
                hardness: -1.0, // Unbreakable
                tool_type: None,
                flammable: false,
                drops: None,
            },
            
            // Wood types
            BlockType::OakLog => BlockProperties {
                name: "Oak Log",
                solid: true,
                transparent: false,
                fluid: false,
                gravity_affected: false,
                light_emission: 0,
                blast_resistance: 2.0,
                hardness: 2.0,
                tool_type: Some("axe"),
                flammable: true,
                drops: Some(BlockType::OakLog),
            },
            BlockType::BirchLog => BlockProperties {
                name: "Birch Log",
                solid: true,
                transparent: false,
                fluid: false,
                gravity_affected: false,
                light_emission: 0,
                blast_resistance: 2.0,
                hardness: 2.0,
                tool_type: Some("axe"),
                flammable: true,
                drops: Some(BlockType::BirchLog),
            },
            BlockType::SpruceLog => BlockProperties {
                name: "Spruce Log",
                solid: true,
                transparent: false,
                fluid: false,
                gravity_affected: false,
                light_emission: 0,
                blast_resistance: 2.0,
                hardness: 2.0,
                tool_type: Some("axe"),
                flammable: true,
                drops: Some(BlockType::SpruceLog),
            },
            BlockType::OakPlanks => BlockProperties {
                name: "Oak Planks",
                solid: true,
                transparent: false,
                fluid: false,
                gravity_affected: false,
                light_emission: 0,
                blast_resistance: 3.0,
                hardness: 2.0,
                tool_type: Some("axe"),
                flammable: true,
                drops: Some(BlockType::OakPlanks),
            },
            BlockType::BirchPlanks => BlockProperties {
                name: "Birch Planks",
                solid: true,
                transparent: false,
                fluid: false,
                gravity_affected: false,
                light_emission: 0,
                blast_resistance: 3.0,
                hardness: 2.0,
                tool_type: Some("axe"),
                flammable: true,
                drops: Some(BlockType::BirchPlanks),
            },
            BlockType::SprucePlanks => BlockProperties {
                name: "Spruce Planks",
                solid: true,
                transparent: false,
                fluid: false,
                gravity_affected: false,
                light_emission: 0,
                blast_resistance: 3.0,
                hardness: 2.0,
                tool_type: Some("axe"),
                flammable: true,
                drops: Some(BlockType::SprucePlanks),
            },
            
            // Leaves
            BlockType::OakLeaves => BlockProperties {
                name: "Oak Leaves",
                solid: true,
                transparent: true,
                fluid: false,
                gravity_affected: false,
                light_emission: 0,
                blast_resistance: 0.2,
                hardness: 0.2,
                tool_type: Some("shears"),
                flammable: true,
                drops: None, // Can drop saplings randomly
            },
            BlockType::BirchLeaves => BlockProperties {
                name: "Birch Leaves",
                solid: true,
                transparent: true,
                fluid: false,
                gravity_affected: false,
                light_emission: 0,
                blast_resistance: 0.2,
                hardness: 0.2,
                tool_type: Some("shears"),
                flammable: true,
                drops: None, // Can drop saplings randomly
            },
            BlockType::SpruceLeaves => BlockProperties {
                name: "Spruce Leaves",
                solid: true,
                transparent: true,
                fluid: false,
                gravity_affected: false,
                light_emission: 0,
                blast_resistance: 0.2,
                hardness: 0.2,
                tool_type: Some("shears"),
                flammable: true,
                drops: None, // Can drop saplings randomly
            },
            
            // Ores and minerals
            BlockType::CoalOre => BlockProperties {
                name: "Coal Ore",
                solid: true,
                transparent: false,
                fluid: false,
                gravity_affected: false,
                light_emission: 0,
                blast_resistance: 3.0,
                hardness: 3.0,
                tool_type: Some("pickaxe"),
                flammable: false,
                drops: Some(BlockType::CoalOre), // Actually drops coal item
            },
            BlockType::IronOre => BlockProperties {
                name: "Iron Ore",
                solid: true,
                transparent: false,
                fluid: false,
                gravity_affected: false,
                light_emission: 0,
                blast_resistance: 3.0,
                hardness: 3.0,
                tool_type: Some("pickaxe"),
                flammable: false,
                drops: Some(BlockType::IronOre), // Actually drops iron ore
            },
            BlockType::GoldOre => BlockProperties {
                name: "Gold Ore",
                solid: true,
                transparent: false,
                fluid: false,
                gravity_affected: false,
                light_emission: 0,
                blast_resistance: 3.0,
                hardness: 3.0,
                tool_type: Some("pickaxe"),
                flammable: false,
                drops: Some(BlockType::GoldOre), // Actually drops gold ore
            },
            BlockType::RedstoneOre => BlockProperties {
                name: "Redstone Ore",
                solid: true,
                transparent: false,
                fluid: false,
                gravity_affected: false,
                light_emission: 0,
                blast_resistance: 3.0,
                hardness: 3.0,
                tool_type: Some("pickaxe"),
                flammable: false,
                drops: Some(BlockType::RedstoneOre), // Actually drops redstone dust
            },
            BlockType::DiamondOre => BlockProperties {
                name: "Diamond Ore",
                solid: true,
                transparent: false,
                fluid: false,
                gravity_affected: false,
                light_emission: 0,
                blast_resistance: 3.0,
                hardness: 3.0,
                tool_type: Some("pickaxe"),
                flammable: false,
                drops: Some(BlockType::DiamondOre), // Actually drops diamond
            },
            
            // Processed materials
            BlockType::Glass => BlockProperties {
                name: "Glass",
                solid: true,
                transparent: true,
                fluid: false,
                gravity_affected: false,
                light_emission: 0,
                blast_resistance: 0.3,
                hardness: 0.3,
                tool_type: None,
                flammable: false,
                drops: None, // Doesn't drop anything
            },
            BlockType::Brick => BlockProperties {
                name: "Bricks",
                solid: true,
                transparent: false,
                fluid: false,
                gravity_affected: false,
                light_emission: 0,
                blast_resistance: 6.0,
                hardness: 2.0,
                tool_type: Some("pickaxe"),
                flammable: false,
                drops: Some(BlockType::Brick),
            },
            BlockType::Cobblestone => BlockProperties {
                name: "Cobblestone",
                solid: true,
                transparent: false,
                fluid: false,
                gravity_affected: false,
                light_emission: 0,
                blast_resistance: 6.0,
                hardness: 2.0,
                tool_type: Some("pickaxe"),
                flammable: false,
                drops: Some(BlockType::Cobblestone),
            },
            BlockType::StoneBrick => BlockProperties {
                name: "Stone Bricks",
                solid: true,
                transparent: false,
                fluid: false,
                gravity_affected: false,
                light_emission: 0,
                blast_resistance: 6.0,
                hardness: 1.5,
                tool_type: Some("pickaxe"),
                flammable: false,
                drops: Some(BlockType::StoneBrick),
            },
            
            // Fluids
            BlockType::Water => BlockProperties {
                name: "Water",
                solid: false,
                transparent: true,
                fluid: true,
                gravity_affected: false,
                light_emission: 0,
                blast_resistance: 100.0,
                hardness: 100.0,
                tool_type: None,
                flammable: false,
                drops: None,
            },
            BlockType::Lava => BlockProperties {
                name: "Lava",
                solid: false,
                transparent: true,
                fluid: true,
                gravity_affected: false,
                light_emission: 15,
                blast_resistance: 100.0,
                hardness: 100.0,
                tool_type: None,
                flammable: false,
                drops: None,
            },
            
            // Plants
            BlockType::TallGrass => BlockProperties {
                name: "Tall Grass",
                solid: false,
                transparent: true,
                fluid: false,
                gravity_affected: false,
                light_emission: 0,
                blast_resistance: 0.0,
                hardness: 0.0,
                tool_type: None,
                flammable: true,
                drops: None,
            },
            BlockType::Flower => BlockProperties {
                name: "Flower",
                solid: false,
                transparent: true,
                fluid: false,
                gravity_affected: false,
                light_emission: 0,
                blast_resistance: 0.0,
                hardness: 0.0,
                tool_type: None,
                flammable: true,
                drops: Some(BlockType::Flower),
            },
            
            // Special
            BlockType::Torch => BlockProperties {
                name: "Torch",
                solid: false,
                transparent: true,
                fluid: false,
                gravity_affected: false,
                light_emission: 14,
                blast_resistance: 0.0,
                hardness: 0.0,
                tool_type: None,
                flammable: false,
                drops: Some(BlockType::Torch),
            },
            BlockType::Chest => BlockProperties {
                name: "Chest",
                solid: true,
                transparent: false,
                fluid: false,
                gravity_affected: false,
                light_emission: 0,
                blast_resistance: 2.5,
                hardness: 2.5,
                tool_type: Some("axe"),
                flammable: true,
                drops: Some(BlockType::Chest),
            },
            BlockType::Crafting => BlockProperties {
                name: "Crafting Table",
                solid: true,
                transparent: false,
                fluid: false,
                gravity_affected: false,
                light_emission: 0,
                blast_resistance: 2.5,
                hardness: 2.5,
                tool_type: Some("axe"),
                flammable: true,
                drops: Some(BlockType::Crafting),
            },
            BlockType::Furnace => BlockProperties {
                name: "Furnace",
                solid: true,
                transparent: false,
                fluid: false,
                gravity_affected: false,
                light_emission: 0,
                blast_resistance: 3.5,
                hardness: 3.5,
                tool_type: Some("pickaxe"),
                flammable: false,
                drops: Some(BlockType::Furnace),
            },
        }
    }
    
    /// Returns the block type from a numeric ID
    pub fn from_id(id: u16) -> Option<Self> {
        match id {
            0 => Some(BlockType::Air),
            1 => Some(BlockType::Stone),
            2 => Some(BlockType::Dirt),
            3 => Some(BlockType::Grass),
            4 => Some(BlockType::Sand),
            5 => Some(BlockType::Gravel),
            6 => Some(BlockType::Bedrock),
            10 => Some(BlockType::OakLog),
            11 => Some(BlockType::BirchLog),
            12 => Some(BlockType::SpruceLog),
            13 => Some(BlockType::OakPlanks),
            14 => Some(BlockType::BirchPlanks),
            15 => Some(BlockType::SprucePlanks),
            20 => Some(BlockType::OakLeaves),
            21 => Some(BlockType::BirchLeaves),
            22 => Some(BlockType::SpruceLeaves),
            30 => Some(BlockType::CoalOre),
            31 => Some(BlockType::IronOre),
            32 => Some(BlockType::GoldOre),
            33 => Some(BlockType::RedstoneOre),
            34 => Some(BlockType::DiamondOre),
            40 => Some(BlockType::Glass),
            41 => Some(BlockType::Brick),
            42 => Some(BlockType::Cobblestone),
            43 => Some(BlockType::StoneBrick),
            50 => Some(BlockType::Water),
            51 => Some(BlockType::Lava),
            60 => Some(BlockType::TallGrass),
            61 => Some(BlockType::Flower),
            70 => Some(BlockType::Torch),
            71 => Some(BlockType::Chest),
            72 => Some(BlockType::Crafting),
            73 => Some(BlockType::Furnace),
            _ => None,
        }
    }
    
    /// Returns all block types
    pub fn all() -> Vec<Self> {
        vec![
            BlockType::Air,
            BlockType::Stone,
            BlockType::Dirt,
            BlockType::Grass,
            BlockType::Sand,
            BlockType::Gravel,
            BlockType::Bedrock,
            BlockType::OakLog,
            BlockType::BirchLog,
            BlockType::SpruceLog,
            BlockType::OakPlanks,
            BlockType::BirchPlanks,
            BlockType::SprucePlanks,
            BlockType::OakLeaves,
            BlockType::BirchLeaves,
            BlockType::SpruceLeaves,
            BlockType::CoalOre,
            BlockType::IronOre,
            BlockType::GoldOre,
            BlockType::RedstoneOre,
            BlockType::DiamondOre,
            BlockType::Glass,
            BlockType::Brick,
            BlockType::Cobblestone,
            BlockType::StoneBrick,
            BlockType::Water,
            BlockType::Lava,
            BlockType::TallGrass,
            BlockType::Flower,
            BlockType::Torch,
            BlockType::Chest,
            BlockType::Crafting,
            BlockType::Furnace,
        ]
    }
    
    /// Returns the name of the block type
    pub fn name(&self) -> &'static str {
        self.properties().name
    }
} 